### PR TITLE
Add windows support

### PR DESCRIPTION
**Pull request by sixohsix**
Hi!

This PR adds Windows support. I was a bit surprised that this actually worked, but thanks to rtmidi and py_audio, your software was really easy to adapt.

After applying these patches, it should still work with OS X and Linux as it did before, but please test that to be sure.

The commit comments explain what every change is. Please let me know if you have any questions.

Thanks for this fun program!

### CODE REVIEW

**Comment by sixohsix** [comment]
Woo! Travis likes it!

**Comment by nandoflorestan** [comment]
This pull request was extremely well written. It is an excellent job and I can attest that it is working fine right now in my Windows machine.

The numpy upgrade is necessary because this newer version is easy to install on Windows, while the older one was a nightmare.

+1 for merging this.

(Maybe I should mention that my branch "nando" has this merged with latest master, but actually it is very easy for you to merge directly.)

And yes, thanks for sharing a VERY useful program!

**Comment by nandoflorestan** [comment]
By the way, it still works just fine in Linux, too.

**Comment by sixohsix** [comment]
@psobot I'm glad you're back! I thought you just really didn't like Windows for some reason. 😢 

This PR has conflicts, but I think #6 includes all of these commits rebased/merged in a nice way. Feel free to close this one, if you prefer.

**Pull request merged**
